# Generated by Django 5.1.2 on 2024-10-28 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime of creation of this record.', verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime of last update of this record.', verbose_name='Updated Time')),
                ('deleted_at', models.DateTimeField(help_text='Datetime of deletion of this record. null mean "not deleted".', null=True, verbose_name='Deleted Time')),
                ('name', models.CharField(help_text='Name of this tag.', max_length=28, verbose_name='Name')),
                ('category', models.IntegerField(choices=[(1, 'Type'), (2, 'Techno'), (3, 'Contrat')], default=1, help_text='Category of this tag.', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime of creation of this record.', verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime of last update of this record.', verbose_name='Updated Time')),
                ('deleted_at', models.DateTimeField(help_text='Datetime of deletion of this record. null mean "not deleted".', null=True, verbose_name='Deleted Time')),
                ('is_published', models.BooleanField(default=False, help_text='If this value set True, users can access this proposal.', verbose_name='Publish Flag')),
                ('title', models.CharField(help_text='Title of this proposal.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Description of this proposal.', max_length=500, verbose_name='Description')),
                ('author', models.ForeignKey(help_text='Author of this proposal.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ManyToManyField(help_text='Tags related of this proposal.', related_name='tags', to='api.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('zip_code', models.IntegerField(verbose_name='Zip Code')),
                ('user_goal_type', models.IntegerField(choices=[(1, 'Collaborator'), (2, 'Collaboration')], default=1, verbose_name='User Goal Type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ('-user__created_at',),
            },
        ),
    ]
