# Generated by Django 5.1.2 on 2024-10-27 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',), 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-user__created_at',), 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Datetime of creation of this record.', verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Name of this tag.', max_length=28, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Datetime of last update of this record.', verbose_name='Updated Time'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime of creation of this record.', verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime of last update of this record.', verbose_name='Updated Time')),
                ('is_published', models.BooleanField(default=False, help_text='If this value set True, users can access this proposal.', verbose_name='Publish Flag')),
                ('title', models.CharField(help_text='Title of this proposal.', max_length=100, verbose_name='Title')),
                ('description', models.TextField(help_text='Description of this proposal.', max_length=500, verbose_name='Description')),
                ('author', models.ForeignKey(help_text='Author of this proposal.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('tags', models.ManyToManyField(help_text='Tags related of this proposal.', related_name='tags', to='api.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'ordering': ('-updated_at',),
            },
        ),
    ]
