# Generated by Django 5.1.2 on 2024-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tag_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deleted_at',
            field=models.DateTimeField(help_text='Datetime of deletion of this record. null mean "not deleted".', null=True, verbose_name='Deleted Time'),
        ),
        migrations.AddField(
            model_name='tag',
            name='deleted_at',
            field=models.DateTimeField(help_text='Datetime of deletion of this record. null mean "not deleted".', null=True, verbose_name='Deleted Time'),
        ),
    ]
