# Generated by Django 5.1.2 on 2024-10-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usermatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatch',
            name='state',
            field=models.IntegerField(choices=[(1, 'Matched'), (2, 'Dismatched'), (3, 'Maybe')], verbose_name='State'),
        ),
    ]
