# Generated by Django 5.1.2 on 2024-10-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usermatch_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='cv_file',
            field=models.FileField(blank=True, help_text='Upload a CV document related to this proposal.', null=True, upload_to='cvs/', verbose_name='CV File'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload a video file related to this proposal.', null=True, upload_to='videos/', verbose_name='Video File'),
        ),
    ]
