# Generated by Django 5.1.2 on 2024-10-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermatch',
            name='state',
            field=models.IntegerField(choices=[(1, 'Matched'), (2, 'Dismatched')], verbose_name='State'),
        ),
    ]
