# Generated by Django 5.1.2 on 2024-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_proposal_description_remove_proposal_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='type',
            field=models.IntegerField(choices=[(1, 'CV'), (2, 'Announcement')], default=1, verbose_name='Proposal Type'),
        ),
    ]
