# Generated by Django 5.1.2 on 2024-11-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_proposal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermatch',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_goal_type',
            field=models.IntegerField(choices=[(1, 'CV'), (2, 'Announcement')], default=1, verbose_name='User Goal Type'),
        ),
    ]
